// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using AuraGenie.Data.Models;
using Microsoft.EntityFrameworkCore;

namespace AuraGenie.Data.Context;

public partial class AuraContext : DbContext
{
    public AuraContext(DbContextOptions<AuraContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuraPointsLog> AuraPointsLogs { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuraPointsLog>(entity =>
        {
            entity.ToTable("AuraPointsLog");

            entity.HasOne(d => d.SourceMessage).WithMany(p => p.AuraPointsLogs).HasForeignKey(d => d.SourceMessageId);

            entity.HasOne(d => d.User).WithMany(p => p.AuraPointsLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasOne(d => d.ReplyMessage).WithMany(p => p.InverseReplyMessage).HasForeignKey(d => d.ReplyMessageId);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}